name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Build an image for tests in client folder
      - name: Build test image
        run: docker build -t mustafa159/react-test -f ./client/Dockerfile.dev ./client

      # 2. Run the tests
      - name: Run tests
        run: docker run -e CI=true mustafa159/react-test npm test -- --coverage

      # 3. Build all the project images
      - name: Build client image
        run: docker build -t mustafa159/multi-client ./client

      - name: Build nginx image
        run: docker build -t mustafa159/multi-nginx ./nginx

      - name: Build server image
        run: docker build -t mustafa159/multi-server ./server

      - name: Build worker image
        run: docker build -t mustafa159/multi-worker ./worker

      # 4. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Push images to Docker Hub
      - name: Push client image
        run: docker push mustafa159/multi-client

      - name: Push nginx image
        run: docker push mustafa159/multi-nginx

      - name: Push server image
        run: docker push mustafa159/multi-server

      - name: Push worker image
        run: docker push mustafa159/multi-worker
      

      # 6. Deploy to AWS production
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-511194960722
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip